"""empty message

Revision ID: afd3edfe6b04
Revises: be0b0bca6b78
Create Date: 2018-04-02 20:27:07.724430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd3edfe6b04'
down_revision = 'be0b0bca6b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bus-route',
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('bus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], )
    )
    op.create_table('bus_stop-route',
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['bus_stops.id'], )
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('home_stop_id', sa.Integer(), nullable=True),
    sa.Column('school_stop', sa.Text(), nullable=True),
    sa.Column('present', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['home_stop_id'], ['bus_stops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('trip_start', sa.DateTime(), nullable=False),
    sa.Column('trip_end', sa.DateTime(), nullable=True),
    sa.Column('bus_stop', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_history')
    op.drop_table('students')
    op.drop_table('bus_stop-route')
    op.drop_table('bus-route')
    op.drop_table('routes')
    op.drop_table('buses')
    op.drop_table('bus_stops')
    # ### end Alembic commands ###
