"""empty message

Revision ID: b33f7b3f38bc
Revises: 36bc6a89f505
Create Date: 2018-04-03 09:36:32.254422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33f7b3f38bc'
down_revision = '36bc6a89f505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_history', 'bus_stop')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_history', sa.Column('bus_stop', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
