"""Trip history model

Revision ID: e16418159e97
Revises: 68f3dbbeb5da
Create Date: 2018-03-29 12:07:42.048237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e16418159e97'
down_revision = '68f3dbbeb5da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('trip_start', sa.DateTime(), nullable=True),
    sa.Column('trip_end', sa.DateTime(), nullable=True),
    sa.Column('bus_stop', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_history')
    # ### end Alembic commands ###
