"""empty message

Revision ID: f48a79808cbb
Revises: b33f7b3f38bc
Create Date: 2018-04-03 09:37:21.417072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48a79808cbb'
down_revision = 'b33f7b3f38bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_history', sa.Column('bus_stop', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trip_history', 'bus_stops', ['bus_stop'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip_history', type_='foreignkey')
    op.drop_column('trip_history', 'bus_stop')
    # ### end Alembic commands ###
